FROM rocker/verse:4.4.3
LABEL org.opencontainers.image.created="2025-03-10" \
    org.opencontainers.image.authors="Lucille Delisle" \
    org.opencontainers.image.description="Docker image based on rocker:verse with more packages" \
    org.opencontainers.image.title="verse_with_more_packages" \
    org.opencontainers.image.url="https://github.com/lldelisle/lldelisle-docker/blob/main/verse_with_more_packages" \
    org.opencontainers.image.source="https://github.com/lldelisle/lldelisle-docker/blob/main/verse_with_more_packages/image/Dockerfile"
# Copy the file with the list of packages
COPY helpers/packages.to.install_4.4.3_0.txt /tmp/
# Add the libhdf5-dev and patch for hdf5r, libudunits2-dev for units for sf, libgdal-dev for sf,  libgsl-dev library needed for DirichletMultinomial, libboost-filesystem-dev libboost-system-dev for velocyto.R
# Add python for scvelo
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    libhdf5-dev \
    libudunits2-dev \
    patch \
    libgdal-dev \
    libgsl-dev \
    libboost-filesystem-dev libboost-system-dev \
    python3 \
    python3-venv \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*
# Install python scvelo
RUN python3 -m venv /root/venv; . /root/venv/bin/activate; pip install anndata scvelo 'numpy<2' 'scipy<1.14.0'
# Install R packages from CRAN and Bioconductor
RUN R -e 'install.packages("BiocManager");my.packages <- read.delim("/tmp/packages.to.install_4.4.3_0.txt", header = FALSE)[, 1]; BiocManager::install(my.packages, update = FALSE, ask = FALSE)'
# Install other packages
# The .Renviron contains the GITHUB_PAT
RUN --mount=type=secret,id=renv,target=/root/.Renviron \
    R -e 'remotes::install_github("satijalab/seurat-wrappers", upgrade = "never", ref = "8d46d6c47c089e193fe5c02a8c23970715918aa9");remotes::install_github("cellgeni/sceasy", ref = "c1c0bf973b0b3b67e013c01bf583d1fcc4c9f8cc", upgrade = "never");remotes::install_github("lldelisle/velocyto.R", ref = "comment_rf_warning", upgrade = "never");remotes::install_github("immunogenomics/presto", upgrade = "never", ref = "7636b3d0465c468c35853f82f1717d3a64b3c8f6");remotes::install_github("lldelisle/usefulLDfunctions", upgrade = "never", ref = "v0.1.6");remotes::install_github("chris-mcginnis-ucsf/DoubletFinder", upgrade = "never", ref = "b86c53ab8940602f0aeb8cd27315482a3efb83f0");remotes::install_github("mojaveazure/seurat-disk", upgrade = "never", ref = "877d4e18ab38c686f5db54f8cd290274ccdbe295");remotes::install_github("cole-trapnell-lab/monocle3", upgrade = "never", ref = "98402ed0c10cac020524bebbb9300614a799f6d1")'
# Install another round of R packages from CRAN and Bioconductor
COPY helpers/packages.to.install_4.4.3_1.txt /tmp/
RUN R -e 'install.packages("BiocManager");my.packages <- read.delim("/tmp/packages.to.install_4.4.3_1.txt", header = FALSE)[, 1]; BiocManager::install(my.packages, update = FALSE, ask = FALSE)'
# Install DoubletFinder
# The .Renviron contains the GITHUB_PAT
RUN --mount=type=secret,id=renv,target=/root/.Renviron \
    R -e 'remotes::install_github("chris-mcginnis-ucsf/DoubletFinder", upgrade = "never", ref = "1b244d8f0d54b4b1cb4365639931bbb16f01e1cd")'
# Install the windows fonts
# Thanks to https://stackoverflow.com/a/77216646
RUN apt-get update \
    && echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | debconf-set-selections \
    && DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends ttf-mscorefonts-installer \
    && rm -rf /var/lib/apt/lists/*
# Build font cache
RUN fc-cache -f
# Install another round of R packages from CRAN and Bioconductor
COPY helpers/packages.to.install_4.4.3_2.txt /tmp/
RUN R -e 'install.packages("BiocManager");my.packages <- read.delim("/tmp/packages.to.install_4.4.3_2.txt", header = FALSE)[, 1]; BiocManager::install(my.packages, update = FALSE, ask = FALSE)'
# Load the fonts
RUN R -e 'library(extrafont);font_import(prompt = FALSE);loadfonts(device = "all")'
# Add tk for tcltk (see https://github.com/rocker-org/rocker-versioned2/issues/760)
RUN apt-get update \
    && apt-get install -y --no-install-recommends tk \
    && rm -rf /var/lib/apt/lists/*
COPY helpers/install_RePACT.R /tmp/
RUN Rscript /tmp/install_RePACT.R
